baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Prickly Paradigm Press"
author = "Prickly Paradigm"
googleAnalytics = ""
enableRobotsTXT = true
paginate = 0
theme = "terrassa"

[params]
logo = "images/logo.png"
favicon = "images/favicon.ico"
description = ""

[params.contact]
email = "info@prickly-paradigm.com"
phone = ""
skype = ""
address = "5629 S University Ave, Chicago, IL 60637"

[params.separator]
show = false

[params.social]
youtube = ""
github = ""
facebook = "https://facebook.com/john"
flickr = ""
weibo = ""
mastodon = ""
codepen = ""
instagram = "https://instagram.com/john"
twitter = "https://twitter.com/john"
pinterest = ""
gitlab = ""
tumblr = ""
500px = ""
linkedin = ""

[params.cta]
show = true
cta = "Our Titles"
link = "titles"

[params.posts]
showAuthor = false
showDate = true
showTags = true
dateFormat = "2 January 2006"

[params.copy]
copy = ""

[params.languageSwitcher]
show = false

[params.hero]
textColor = ""

[params.fa]
version = "5.7.2"
integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[privacy]

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = false

[privacy.twitter]
disable = false
enableDNT = true
simple = false

[privacy.vimeo]
disable = false
simple = false

[privacy.youtube]
disable = false
privacyEnhanced = true