baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Prickly Paradigm Press"
author = "Prickly Paradigm"
googleAnalytics = ""
enableRobotsTXT = true
paginate = 100
theme = "terrassa"

[params]
logo = "images/logo.png"
favicon = "images/favicon.ico"
description = "Prickly Paradigm Press, LLC is devoted to giving serious authors free rein to say what's right and what's wrong about their disciplines and about the world, including what's never been said before. The result is intellectuals unbound, writing unconstrained and creative texts about meaningful matters."

[params.contact]
email = "info@prickly-paradigm.com"
phone = ""
skype = ""
address = "5751 S. Woodlawn Ave., Chicago, IL 60637"

[params.separator]
show = false

[params.social]
youtube = ""
github = ""
facebook = ""
flickr = ""
weibo = ""
mastodon = ""
codepen = ""
instagram = ""
twitter = ""
pinterest = ""
gitlab = ""
tumblr = ""
500px = ""
linkedin = ""

[params.cta]
show = false
cta = "Recent Titles"
link = "#section-1"

[params.posts]
showAuthor = false
showDate = true
showTags = true
dateFormat = "January 2006"

[params.copy]
copy = ""

[params.languageSwitcher]
show = false

[params.hero]
textColor = ""

[params.fa]
version = "5.7.2"
integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[privacy]

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = false

[privacy.twitter]
disable = false
enableDNT = true
simple = false

[privacy.vimeo]
disable = false
simple = false

[privacy.youtube]
disable = false
privacyEnhanced = true