backend:
  name: git-gateway
media_folder: static/images
public_folder: /images
collections:
  - name: 'posts'
    label: 'News'
    folder: 'content/en/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
